In [1]:
import  numpy as np
import pandas as pd

In [2]:

df = pd.read_csv('C:/Users/ASUS/OneDrive/Desktop/jupyter projects/employee_data.csv')

In [3]:
df.head()

,Employee_ID,Name,Age,Salary,Department,Experience (Years),City,Gender,Performance Score
0,101,Employee_1,50,110592,HR,9,Denver,Female,84
1,102,Employee_2,36,48110,IT,29,San Diego,Male,92
2,103,Employee_3,29,119309,IT,26,Chicago,Female,97
3,104,Employee_4,42,67266,Marketing,25,Seattle,Male,65
4,105,Employee_5,40,92992,Finance,24,Boston,Male,91

In [4]:
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [5]:
df

,Employee_ID,Name,Age,Salary,Department,Experience (Years),City,Gender,Performance Score
0,101,Employee_1,50,110592,HR,9,Denver,Female,84
1,102,Employee_2,36,48110,IT,29,San Diego,Male,92
2,103,Employee_3,29,119309,IT,26,Chicago,Female,97
3,104,Employee_4,42,67266,Marketing,25,Seattle,Male,65
4,105,Employee_5,40,92992,Finance,24,Boston,Male,91
...,...,...,...,...,...,...,...,...,...
95,196,Employee_96,58,51111,IT,33,Los Angeles,Female,63
96,197,Employee_97,56,77504,IT,12,Denver,Male,60
97,198,Employee_98,43,41802,IT,3,Boston,Male,99
98,199,Employee_99,48,48155,HR,1,Boston,Female,91
99,200,Employee_100,56,113656,HR,33,Chicago,Male,93

In [6]:
df.drop(['Name', 'Department','Gender', 'Performance Score' ], axis=1, inplace=True)

In [7]:
df.head()

   Employee_ID  Age  Salary  Experience (Years)       City
0          101   50  110592                   9     Denver
1          102   36   48110                  29  San Diego
2          103   29  119309                  26    Chicago
3          104   42   67266                  25    Seattle
4          105   40   92992                  24     Boston

In [8]:
df.isna().sum()

Employee_ID           0
Age                   0
Salary                0
Experience (Years)    0
City                  0
dtype: int64

In [9]:
df = df.drop('Employee_ID', axis=1)

In [10]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
df['City'] = label_encoder.fit_transform(df['City'])

In [11]:
df.head()

   Age  Salary  Experience (Years)  City
0   50  110592                   9     2
1   36   48110                  29     6
2   29  119309                  26     1
3   42   67266                  25     7
4   40   92992                  24     0

In [12]:
y = df['Salary']
X = df.drop('Salary', axis=1)

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [14]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X_train, y_train)

GaussianNB()

In [15]:
y_pred = model.predict(X_test)

In [16]:
y_pred

array([ 82941,  89080,  83585,  47392, 107172,  66736,  89080,  84262,
        70080,  42693, 115766,  47392,  74766,  58141, 102003, 105318,
       106199,  74754, 107214,  74754,  61834,  63664,  78623, 119309,
        90859,  91005,  89080,  79353,  98053, 111295])

In [17]:

from sklearn.metrics import accuracy_score, classification_report


print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.0